name: release-github-action

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build'
        required: true
        type: string
      version:
        description: 'Version to release'
        required: true
        type: string
      update-base-tag:
        description: 'Update base tag'
        type: boolean
        default: false

jobs:
  release-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew cli:shadowJar

      - name: Copy binary
        run: mkdir -p release && mv cli/build/libs/exporter-cli.jar release

      - name: Commit binary
        uses: EndBug/add-and-commit@v9
        with:
          add: 'release/exporter-cli.jar'
          message: 'Release ${{ inputs.version }}'
          new_branch: 'release/${{ inputs.version }}'
          tag: '${{ inputs.version }} --force'
          tag_push: '--force'

      - name: Create release
        run: gh release create ${{ inputs.version }} release/exporter-cli.jar --target release/${{ inputs.version }} --title ${{ inputs.version }} --latest --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Calculate major version tag
        run: echo "MAJOR_VERSION_TAG=$(echo ${{ inputs.version }} | cut -d '.' -f 1)" >> $GITHUB_ENV
        if: ${{ inputs.update-base-tag }}

      - name: Update major version tag
        if: ${{ inputs.update-base-tag }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.MAJOR_VERSION_TAG }}
          force_push_tag: true
          commit_sha: release/${{ inputs.version }}
